# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bind = SUPER SHIFT, m,exec, hyprctl dispatch layoutmsg swapwithmaster 
bind = SUPER, m,exec, hyprctl dispatch layoutmsg focusmaster 
bindd = SUPER, RETURN, Terminal,exec, ghostty
bindd = SUPER , w, Browser, exec, $browser
bindd = SUPER SHIFT , w, Browser (private), exec, $browser --private
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bind  = SUPER SHIFT,Return,exec,rofi-launcher
bind  = SUPER SHIFT,Backspace,exec,wlogout
