env = GDK_SCALE,1
monitor=,preferred,auto,auto

workspace = name:c,monitor:HDMI-A-1,persistent:true
workspace = name:r,monitor:HDMI-A-1,persistent:true

bindd = SUPER, c, Switch to workspace codding , workspace, codding
bindd = SUPER, r, Switch to workspace reading , workspace, reading

bindd = SUPER SHIFT, c, Move window to workspace codding, movetoworkspace, codding
bindd = SUPER SHIFT, r, Move window to workspace reading, movetoworkspace, reading

